contact/urls.py
from contact import views
from django.urls import path

app_name = 'contact'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    #contact (CRUD)
    path('contact/<int:contact_id>/', views.contact, name='contact'),
    path('contact/create/', views.create, name='create'),
    path('contact/<int:contact_id>/update/', views.update, name='update'),
    path('contact/<int:contact_id>/delete/', views.delete, name='delete'),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('contact.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.STATIC_ROOT)

contact/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        
    name = models.CharField(max_length=50)
    
    def __str__(self) -> str:
        return self.name

    
class Contact(models.Model):
    class Meta:
        verbose_name = 'Contato'
        verbose_name_plural = 'Contatos'
        
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=50, blank=True)
    email = models.EmailField(max_length=254, blank=True)
    create_date = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True)
    show = models.BooleanField(default=True)
    picture = models.ImageField(blank=True, upload_to='pictures/%Y/%M/')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL,
                                 blank=True, null=True)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL,
                                 blank=True, null=True)
    
    
    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'

contact/forms.py
from django import forms
from django.core.exceptions import ValidationError
from . import models

class ContactForm(forms.ModelForm):
    picture = forms.ImageField(
        widget=forms.FileInput(
            attrs={
                'accept': 'image/*',
            }
        )
    )

    class Meta:
        model = models.Contact
        fields = (
            'first_name','last_name','phone',
            'email','description','category',
            'picture',

        )
        # Método clean é usada quando precisamos validar campos no formulários,
        # este método é chamado antes de salvar os dados na base de dados

        def clean(self):
            cleaned_data = self.cleaned_data
            self.add_error(
                'first_name',
                ValidationError(
                    'Mensagem de erro',
                    code='invalid'
                )
            )
            self.add_error(
                'first_name',
                ValidationError(
                    'Mensagem de erro 2',
                    code='invalid'
                )
            )
            return super().clean()

contact/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(
        request,
        'contact/index.html'
    )

contact/views/contact_forms.py
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from contact.forms import ContactForm
from contact.models import Contact

def create(request):
    
    form_action = reverse('contact:create')

    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES)

        context = {
            'form': form,
            'form_action': form_action,
        }

        if form.is_valid():
            contact = form.save()
            return redirect('contact:update', contact_id=contact.pk)

        return render(
            request,
            'contact/create.html',
            context
        )

    context = {
        'form': ContactForm(),
        'form_action': form_action,
    }

    return render(
        request,
        'contact/create.html',
        context
    )

def update(request, contact_id):
    contact = get_object_or_404(
        Contact, pk=contact_id, show=True
    )
    form_action = reverse('contact:update', args=(contact_id,))

    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES, instance=contact)

        context = {
            'form': form,
            'form_action': form_action,
        }

        if form.is_valid():
            contact = form.save()
            return redirect('contact:update', contact_id=contact.pk)

        return render(
            request,
            'contact/create.html',
            context
        )

    context = {
        'form': ContactForm(instance=contact),
        'form_action': form_action,
    }

    return render(
        request,
        'contact/create.html',
        context
    )
    
def delete(request, contact_id):
    contact = get_object_or_404(
        Contact, pk=contact_id, show=True
    )
    
    confirmation = request.POST.get('confirmation', 'no')
    
    if confirmation == 'yes':
        contact.delete()
        return redirect('contact:index')
    
    return render(
        request,
        'contact/contact.html',
        {
            'contact': contact,
            'confirmation': confirmation,
        }
    )   

contact/views/contact_views.py
from django.shortcuts import render #type: ignore
from contact.models import Contact
from django.http import Http404
from django.db.models import Q
from django.shortcuts import get_object_or_404, render, redirect
from django.core.paginator import Paginator

# Create your views here.
def index(request):
    #contacts = Contact.objects.all().order_by('-id')
    contacts = Contact.objects.filter(show=True).order_by('-id')

    
    paginator= Paginator(contacts, 15)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    context = {
        'contacts': contacts,
        'page_obj': page_obj,
        'site_title': 'Contatos - '
    }
    
    return render(
        request,
        'contact/index.html',
        context
    )

def contact(request, contact_id):
    #single_contact  = Contact.objects.get(pk=contact_id).first()
    
    single_contact = get_object_or_404(
        Contact.objects, pk=contact_id, show=True
    )
    
    site_title = f'{single_contact.first_name} {single_contact.last_name} - '

    context = {
        'contact': single_contact,
        'site_title': site_title
    }

    return render(
        request,
        'contact/contact.html',
        context
    )
    
def search(request):
    #strip retira espaços do início e fim da string
    search_value = request.GET.get('q', '').strip()
    #print('search_value', search_value)
    #se não digitou nada, redireciona para a home
    #Q possibilita o uso do OU nas consultas SQL
    if search_value == '':
        return redirect('contact:index')
    contacts = Contact.objects.filter(show=True).filter(Q(first_name__icontains=search_value) | 
                                                        Q(last_name__icontains=search_value) | 
                                                        Q(email__icontains=search_value)).order_by('-id')


    paginator= Paginator(contacts, 15)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    
    context = {
        'contacts': contacts,
        'page_obj': page_obj,
        'site_title': 'Search -'
    }
    
    return render(
        request,
        'contact/index.html',
        context
    )

contact/templates/contact/contact.html
{% extends 'global/base.html' %}

{% block content %}
<p><b>Description:</b> {{ contact.description }}</p>
    <p><b>Category:</b> {{ contact.category.name }}</p>

    {% if contact.picture %}
        <p>
            <img src="{{ contact.picture.url }}" alt="{{contact.first_name }} {{ contact.last_name }}">
        </p>
    {% endif %}
        
    <div class="contact-links">
        <a class="btn btn-link" href="{% url 'contact:update' contact.id %}">Update</a>
        
        <form action="{% url 'contact:delete' contact.id %}" method="POST">
            {% csrf_token %}
                {% if confirmation == 'no' %}
                    <input type="hidden" name="confirmation" value="yes">
                    <button class="btn btn-link btn-delete" type="submit">Confirma?</button>
                {% else %}
        <button class="btn btn-link btn-delete" type="submit">Delete</button>
        {% endif %}
        </form>
        </div>
    </div>
{% endblock content %}

contact/templates/contact/create.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="form-wrapper">

    <h2>Contact</h2>

    <form 
      action=" {% url 'contact:create' %}"
      method="POST"
      enctype="multipart/form-data"
    >
      {% csrf_token %}      
      
      <div class="form-content">
        {% for field in form %}
          <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
            {{ field.errors }}
            {% if field.help_text %}
              <p class="help-text">{{ field.help_text }}</p>
            {% endif %}
          </div>

          {% if field.name == 'picture' and field.value.url %}
            <div class="form-group">
              <img src="{{ field.value.url }}" alt="">
            </div>
          {% endif %}
          
        {% endfor %}
      </div>

      {% if form.non_field_errors %}
        <div class="form-content">
          <div class="form-group">
            <div class="message error">
              {{ form.non_field_errors }}
            </div>
          </div>
        </div>
      {% endif %}

      <div class="form-content">
        <div class="form-group">
          <button class="btn" type="submit">Send</button>
        </div>
      </div>

    </form>
  </div>
{% endblock content %}

contact/templates/contact/index.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="responsive-table">
    <table class="contacts-table">
      <caption class="table-caption ">
        Contacts
      </caption>

      <thead>
        <tr class="table-row table-row-header">
          <th class="table-header">ID</th>
          <th class="table-header">First Name</th>
          <th class="table-header">Last Name</th>
          <th class="table-header">Phone</th>
          <th class="table-header">E-mail</th>
        </tr>
      </thead>

      <tbody>
        {% for contact in page_obj %}
          <tr class="table-row">
            <td class="table-cel">
              <a class="table-link" href="{% url 'contact:contact' contact.id %}">
                {{ contact.id }}
              </a>
            </td>
            <td class="table-cel">
              {{ contact.first_name }}
            </td>
            <td class="table-cel">
              {{ contact.last_name }}
            </td>
            <td class="table-cel">
              {{ contact.phone }}
            </td>
            <td class="table-cel">
              {{ contact.email }}
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock content %}